### ISSUE TITLE
Completing labs, yet unable to submit work for completion

### ISSUE THREAD

**Issue by belsonrj** [learn-co-curriculum/ruby-methods-readme#36]
I've satisfied the requirements for two labs in this module, but the "submit" button remains inactive. Am I missing something or is this broken?

**Comment by Gyurn-hash** [comment]
I am having the same issue on every lab, please advise guys

**Comment by maxwellbenton** [comment]
Hi @belsonrj and @Gyurn-hash, 

We are sorry to hear that you are experiencing difficulties submitting your work. If you are still experiencing this issue, please reach out to support@learn.co. GitHub issues are typically reserved for problems with the curriculum content of the lesson the issue is reported on, not those related to the Learn platform or tools.

This issue would also be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

We apologize for any frustration this may have caused you and hope you are able to get assistance via the channels mentioned above. If, after consulting the Help Center and AAQ and support@learn.co, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thank you!
